# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=255, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Note Url')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.Categories', verbose_name='category')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
