# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Note Url')),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='url',
        ),
        migrations.AddField(
            model_name='links',
            name='noteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='notes.Notes', verbose_name='note'),
        ),
    ]
